import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Dutch payment service providers, from Betaalvereniging Nederland.
 *
 * ## The gap this closes
 *
 * A Dutch IBAN carries a four-letter identifier that Betaalvereniging hands to
 * a provider precisely because it issues IBANs. Our curated map keyed Dutch
 * bank codes to BICs, but measured 29/07/2026, all 815 of its Dutch keys are
 * the first four letters of their own BIC. It was never curated: it is derived
 * from the BIC directory, so it confirms a code by comparing it to itself.
 *
 * Holding a Dutch BIC is a different fact from issuing Dutch IBANs. Corporate
 * treasuries hold one for their own SWIFT traffic. The consequence was live in
 * production: a fabricated IBAN carrying SHEL came back verified, with
 * issuer.type 'bank', naming SHELL ASSET MANAGEMENT COMPANY B.V. Panasonic,
 * IMC Trading and SABIC did the same. Those accounts cannot exist, and we were
 * not merely failing to know it, we were asserting the opposite.
 *
 * ## What this list can and cannot say
 *
 * It confirms; it never denies. Betaalvereniging states that listing is
 * voluntary and the overview is therefore incomplete, so an identifier's
 * absence is not evidence that nobody holds it. That is why the Netherlands
 * stays `authoritative: false` and why the signal derived from this file is a
 * separate field rather than a change to bank_code_check.status.
 *
 * Regenerated by scripts/refresh-nl-psp.ts when Betaalvereniging republishes.
 */
export interface NlProvider {
  bic: string;
  name: string;
}

interface NlPspFile {
  source: string;
  as_of: string;
  providers: Record<string, NlProvider>;
}

let cache: NlPspFile | null = null;

function load(): NlPspFile {
  if (!cache) {
    const require = createRequire(import.meta.url);
    cache = require(resolve(__dirname, '../db/nl-psp.json')) as NlPspFile;
  }
  return cache;
}

/** The provider holding a four-letter Dutch identifier, or null if not listed. */
export function lookupNlPsp(identifier: string): NlProvider | null {
  const id = (identifier ?? '').trim().toUpperCase();
  if (!/^[A-Z]{4}$/.test(id)) return null;
  return load().providers[id] ?? null;
}

/** Publication date of the list, so a caller can weigh how stale it may be. */
export function nlPspAsOf(): string {
  return load().as_of;
}

/** How many providers the list names, for the same reason. */
export function nlPspCount(): number {
  return Object.keys(load().providers).length;
}

/** Every listed identifier, for seeding the codes our map is missing. */
export function nlPspEntries(): ReadonlyArray<[string, NlProvider]> {
  return Object.entries(load().providers);
}
