import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { createVerify, generateKeyPairSync } from 'node:crypto';
import {
  CACHE_MAX_AGE_MS,
  cacheAgeMs,
  cachedSummary,
  completeWeeks,
  indexStateOf,
  isSearchConsoleConfigured,
  readSearchConsole,
  relativePath,
  resetSearchConsoleAuth,
  resetSearchConsoleCache,
  SearchConsoleError,
  searchConsoleSummary,
  SITE_URL,
  topRows,
  weeklySeries,
  WITNESS_PATHS,
  windowEnd,
} from './search-console.js';
import { getStatsDB } from './db.js';

/**
 * The Search Console reader, with Google replaced by a stub.
 *
 * The credential is a throwaway RSA pair generated by the test itself: the real
 * service-account key exists only in a production environment variable, and a
 * test that needed it would be a test nobody could run. The stub does not just
 * count calls — it VERIFIES the assertion against the public half and reads the
 * claim set, because the one thing that cannot be checked by looking at this
 * code is whether the bytes we sign are the bytes Google would accept.
 */

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

const ACCOUNT = JSON.stringify({
  client_email: 'gsc-reader@example.iam.gserviceaccount.com',
  private_key: privateKey,
  project_id: 'example',
});

/** Claims of the JWT the module signed, after the signature has been checked. */
interface Claims {
  iss: string;
  scope: string;
  aud: string;
  iat: number;
  exp: number;
}

let assertions: Claims[] = [];
let calls: string[] = [];

function verifyAssertion(assertion: string): Claims {
  const [header, payload, signature] = assertion.split('.');
  const ok = createVerify('RSA-SHA256')
    .update(`${header}.${payload}`)
    .verify(publicKey, Buffer.from(signature, 'base64url'));
  expect(ok).toBe(true);
  expect(JSON.parse(Buffer.from(header, 'base64url').toString())).toEqual({
    alg: 'RS256',
    typ: 'JWT',
  });
  return JSON.parse(Buffer.from(payload, 'base64url').toString()) as Claims;
}

const json = (body: unknown, status = 200): Response =>
  ({ ok: status >= 200 && status < 300, status, json: async () => body }) as Response;

const DAILY = [
  { keys: ['2026-08-10'], clicks: 2, impressions: 100, position: 20 },
  { keys: ['2026-08-16'], clicks: 1, impressions: 300, position: 10 },
  { keys: ['2026-08-28'], clicks: 4, impressions: 40, position: 8 },
  // Monday of the week the window ends in — a week that is not over yet.
  { keys: ['2026-08-31'], clicks: 99, impressions: 9999, position: 1 },
];

const INDEXED = (): Response =>
  json({
    inspectionResult: {
      indexStatusResult: {
        verdict: 'PASS',
        coverageState: 'Submitted and indexed',
        lastCrawlTime: '2026-09-04T22:10:00.000Z',
      },
    },
  });

/** Google up, answering every endpoint the summary touches. */
function googleUp(overrides: { inspect?: (url: string) => Response } = {}) {
  vi.stubGlobal('fetch', async (url: string, init?: RequestInit) => {
    calls.push(String(url));
    if (String(url).startsWith('https://oauth2.googleapis.com/token')) {
      const body = init?.body as URLSearchParams;
      expect(body.get('grant_type')).toBe('urn:ietf:params:oauth:grant-type:jwt-bearer');
      assertions.push(verifyAssertion(String(body.get('assertion'))));
      return json({ access_token: 'stub-token', expires_in: 3600 });
    }
    if (String(url).includes('/searchAnalytics/query')) {
      const sent = JSON.parse(String(init?.body)) as { dimensions: string[] };
      if (sent.dimensions[0] === 'date') return json({ rows: DAILY });
      if (sent.dimensions[0] === 'query') {
        return json({
          rows: [{ keys: ['iban validator'], clicks: 3, impressions: 90, position: 12.44 }],
        });
      }
      return json({
        rows: [{ keys: ['https://ibanforge.com/de/blz'], clicks: 1, impressions: 8, position: 30 }],
      });
    }
    if (String(url).includes('/sitemaps')) {
      return json({
        sitemap: [
          {
            path: 'https://ibanforge.com/sitemap.xml',
            lastSubmitted: '2026-09-06T08:00:00.000Z',
            lastDownloaded: '2026-09-06T09:12:00.000Z',
            contents: [{ submitted: '1394', indexed: '31' }],
            errors: '0',
            warnings: '2',
          },
        ],
      });
    }
    if (String(url).startsWith('https://searchconsole.googleapis.com')) {
      const sent = JSON.parse(String(init?.body)) as { inspectionUrl: string; siteUrl: string };
      expect(sent.siteUrl).toBe(SITE_URL);
      return overrides.inspect?.(sent.inspectionUrl) ?? INDEXED();
    }
    throw new Error(`unexpected call: ${url}`);
  });
}

beforeEach(() => {
  assertions = [];
  calls = [];
  process.env.GSC_SA_JSON = ACCOUNT;
  resetSearchConsoleAuth();
  getStatsDB().exec('DROP TABLE IF EXISTS search_console_cache');
  resetSearchConsoleCache();
});

afterEach(() => {
  vi.unstubAllGlobals();
  delete process.env.GSC_SA_JSON;
  resetSearchConsoleAuth();
});

describe('configuration', () => {
  it('is not configured without the variable, and never throws for it', () => {
    delete process.env.GSC_SA_JSON;
    expect(isSearchConsoleConfigured()).toBe(false);
  });

  it('is not configured on a value that is not a service-account key', () => {
    process.env.GSC_SA_JSON = '{ not json';
    expect(isSearchConsoleConfigured()).toBe(false);
    process.env.GSC_SA_JSON = JSON.stringify({ client_email: 'x@example.com' });
    expect(isSearchConsoleConfigured()).toBe(false);
  });

  it('is configured with a complete key', () => {
    expect(isSearchConsoleConfigured()).toBe(true);
  });
});

describe('the JWT handed to Google', () => {
  it('is signed with the account key and asks for the read-only scope', async () => {
    googleUp();
    await searchConsoleSummary(new Date('2026-09-07T06:00:00Z'));
    expect(assertions).toHaveLength(1);
    const claims = assertions[0];
    expect(claims.iss).toBe('gsc-reader@example.iam.gserviceaccount.com');
    expect(claims.scope).toBe('https://www.googleapis.com/auth/webmasters.readonly');
    expect(claims.aud).toBe('https://oauth2.googleapis.com/token');
    expect(claims.exp - claims.iat).toBe(3600);
  });

  it('is signed once and the token reused for every call of the reading', async () => {
    googleUp();
    await searchConsoleSummary(new Date('2026-09-07T06:00:00Z'));
    // 3 analytics + 1 sitemap + 8 inspections, on one token exchange.
    expect(calls.filter((u) => u.startsWith('https://oauth2.googleapis.com')).length).toBe(1);
    expect(calls.length).toBe(1 + 3 + 1 + WITNESS_PATHS.length);
  });

  it('reports the upstream status when the token is refused', async () => {
    vi.stubGlobal('fetch', async () => json({ error: 'invalid_grant' }, 401));
    await expect(searchConsoleSummary(new Date('2026-09-07T06:00:00Z'))).rejects.toBeInstanceOf(
      SearchConsoleError,
    );
    await expect(searchConsoleSummary(new Date('2026-09-07T06:00:00Z'))).rejects.toMatchObject({
      status: 401,
    });
  });
});

describe('the window and the weeks', () => {
  it('ends three days back, where Search Console actually has data', () => {
    expect(windowEnd(new Date('2026-09-07T06:00:00Z'))).toBe('2026-09-04');
  });

  it('takes four COMPLETE Monday-to-Sunday weeks', () => {
    // 2026-09-04 is a Friday: the week it belongs to is skipped whole.
    expect(completeWeeks('2026-09-04')).toEqual([
      { start: '2026-08-03', end: '2026-08-09' },
      { start: '2026-08-10', end: '2026-08-16' },
      { start: '2026-08-17', end: '2026-08-23' },
      { start: '2026-08-24', end: '2026-08-30' },
    ]);
  });

  it('keeps the week that ends exactly on the window end', () => {
    // 2026-08-30 is a Sunday, so its own week is complete and counts.
    expect(completeWeeks('2026-08-30').at(-1)).toEqual({ start: '2026-08-24', end: '2026-08-30' });
  });
});

describe('weeklySeries', () => {
  const weeks = completeWeeks('2026-09-04');

  it('cuts the daily rows into their weeks', () => {
    const out = weeklySeries(DAILY, weeks);
    expect(out.map((w) => w.clicks)).toEqual([0, 3, 0, 4]);
    expect(out.map((w) => w.impressions)).toEqual([0, 400, 0, 40]);
  });

  it('drops a day of the running week, however loud it is', () => {
    // 2026-08-31 carries 99 clicks and belongs to no complete week. Counted
    // anywhere it would be the biggest column on the card and a third of a week.
    expect(weeklySeries(DAILY, weeks).reduce((n, w) => n + w.clicks, 0)).toBe(7);
  });

  it('weights the position by impressions rather than averaging the days', () => {
    // (20x100 + 10x300) / 400 = 12.5. A plain mean of 20 and 10 would say 15,
    // and would let a day with four impressions move the figure as much as a
    // day with four hundred.
    expect(weeklySeries(DAILY, weeks)[1].position).toBe(12.5);
    expect(weeklySeries(DAILY, weeks)[1].ctr).toBe(0.8);
  });

  it('says null, never zero, for a week Google sent nothing for', () => {
    // Position 0 would print as a rank better than first place.
    expect(weeklySeries(DAILY, weeks)[0]).toMatchObject({ ctr: null, position: null });
  });
});

describe('rows and paths', () => {
  it('makes a page path relative to the site and keeps the root as /', () => {
    expect(relativePath('https://ibanforge.com/fr/audit')).toBe('/fr/audit');
    expect(relativePath('https://ibanforge.com')).toBe('/');
    expect(relativePath('https://elsewhere.example/x')).toBe('https://elsewhere.example/x');
  });

  it('keeps a query verbatim and caps the list', () => {
    const rows = Array.from({ length: 20 }, (_, i) => ({
      keys: [`q ${i}`],
      clicks: i,
      impressions: 10,
      position: 3.14159,
    }));
    const out = topRows(rows, 'query');
    expect(out).toHaveLength(10);
    expect(out[0]).toEqual({ key: 'q 0', clicks: 0, impressions: 10, position: 3.1 });
  });

  it('gives no position to a row with no impression', () => {
    expect(topRows([{ keys: ['q'], clicks: 0, impressions: 0 }], 'query')[0].position).toBeNull();
  });
});

describe('indexStateOf', () => {
  it('reads PASS as indexed', () => {
    expect(indexStateOf({ verdict: 'PASS', coverageState: 'Submitted and indexed' })).toBe(
      'indexed',
    );
  });

  it('separates a URL Google refused from one it has never seen', () => {
    // Both come back NEUTRAL; only the sentence tells them apart, and they are
    // opposite problems — content on one side, discovery on the other.
    expect(
      indexStateOf({ verdict: 'NEUTRAL', coverageState: 'Crawled - currently not indexed' }),
    ).toBe('not-indexed');
    expect(indexStateOf({ verdict: 'NEUTRAL', coverageState: 'URL is unknown to Google' })).toBe(
      'unknown',
    );
  });

  it('is unknown on an empty or missing result', () => {
    expect(indexStateOf({})).toBe('unknown');
    expect(indexStateOf(null)).toBe('unknown');
  });
});

describe('searchConsoleSummary', () => {
  it('assembles the weeks, the two top lists, the sitemap and the eight witnesses', async () => {
    googleUp();
    const s = await searchConsoleSummary(new Date('2026-09-07T06:00:00Z'));
    expect(s.site).toBe(SITE_URL);
    expect(s.window_end).toBe('2026-09-04');
    expect(s.weeks).toHaveLength(4);
    expect(s.top_window).toEqual({ start: '2026-08-08', end: '2026-09-04' });
    expect(s.queries[0]).toEqual({
      key: 'iban validator',
      clicks: 3,
      impressions: 90,
      position: 12.4,
    });
    expect(s.pages[0].key).toBe('/de/blz');
    // Google sends the sitemap counters as decimal strings; concatenated they
    // would read "139431" submitted.
    expect(s.sitemaps[0]).toMatchObject({ submitted: 1394, indexed: 31, warnings: 2 });
    expect(s.inspections.map((i) => i.path)).toEqual([...WITNESS_PATHS]);
    expect(s.inspections[0]).toMatchObject({ state: 'indexed', last_crawled: '2026-09-04' });
  });

  it('lets one witness fail without losing the other seven or the weeks', async () => {
    googleUp({
      inspect: (url) => (url.endsWith('/sk') ? json({ error: {} }, 429) : INDEXED()),
    });
    const s = await searchConsoleSummary(new Date('2026-09-07T06:00:00Z'));
    expect(s.weeks).toHaveLength(4);
    const sk = s.inspections.find((i) => i.path === '/sk');
    expect(sk).toMatchObject({ state: 'unknown', error: 'http_429' });
    expect(s.inspections.filter((i) => i.error === null)).toHaveLength(WITNESS_PATHS.length - 1);
  });
});

describe('the six-hour cache', () => {
  const NOW = new Date('2026-09-07T06:00:00Z');

  it('reads Google once and serves the stored payload afterwards', async () => {
    googleUp();
    const first = await readSearchConsole({ now: NOW });
    const spent = calls.length;
    const second = await readSearchConsole({ now: NOW });
    expect(calls.length).toBe(spent);
    expect(second.summary).toEqual(first.summary);
    expect(second.fetched_at).toBe(first.fetched_at);
  });

  it('goes back to Google on ?refresh=1 even when the payload is young', async () => {
    googleUp();
    await readSearchConsole({ now: NOW });
    const spent = calls.length;
    await readSearchConsole({ refresh: true, now: NOW });
    expect(calls.length).toBeGreaterThan(spent);
  });

  it('refetches once the payload is past six hours', async () => {
    googleUp();
    await readSearchConsole({ now: NOW });
    const spent = calls.length;
    await readSearchConsole({ now: new Date(NOW.getTime() + CACHE_MAX_AGE_MS + 1000) });
    expect(calls.length).toBeGreaterThan(spent);
  });

  it('measures the age of a SQL stamp as UTC', () => {
    expect(cacheAgeMs('2026-09-07 00:00:00', new Date('2026-09-07T06:00:00Z'))).toBe(
      6 * 60 * 60 * 1000,
    );
    expect(cacheAgeMs('not a date', NOW)).toBe(Number.POSITIVE_INFINITY);
  });

  it('keeps the last reading when Google refuses the next one', async () => {
    googleUp();
    const good = await readSearchConsole({ now: NOW });
    vi.stubGlobal('fetch', async () => json({ error: 'rateLimitExceeded' }, 429));
    await expect(readSearchConsole({ refresh: true, now: NOW })).rejects.toMatchObject({
      status: 429,
    });
    // The route serves this, marked stale, rather than an empty card.
    expect(cachedSummary()?.summary).toEqual(good.summary);
  });

  it('has nothing to serve before the first successful reading', () => {
    expect(cachedSummary()).toBeNull();
  });
});
