/**
 * Canonical and hreflang, computed per page.
 *
 * Audit 2026-09-01 (WEB-01, WEB-02, WEB-03). The canonical URL lived in
 * `app/[locale]/layout.tsx`, so every page that did not redeclare it inherited
 * the locale HOME's URL: 52 of 170 pages told a crawler "the canonical version
 * of this page is another page", and 18 of them named `https://ibanforge.com`,
 * which is itself a 307 to `/en`. The only two pages that did redeclare it
 * (`docs/[slug]`, `blog/[slug]`) wrote `alternates: { canonical }` alone, and a
 * segment's `alternates` REPLACES its parent's rather than merging into it, so
 * those 116 content pages lost their `languages` block entirely.
 *
 * The two failures have one shape: metadata that must vary per page was written
 * once, high up. This helper makes the pair inseparable — a caller cannot get a
 * canonical out of it without getting the matching hreflang set.
 *
 * The hreflang keys are `fr` and `de`, not `fr-CH` / `de-CH`: the regional
 * variants offered the French page to francophones IN SWITZERLAND only and left
 * France, Belgium, Luxembourg, Germany and Austria falling through to
 * `x-default`, that is to English. The `ogLocale` values three lines away in the
 * same layout already said `fr_FR` and `de_DE`.
 */

import { localePath } from './locale-path';

export const SITE_URL = 'https://ibanforge.com';

/** Mirrors `i18n/routing.ts`. Kept as a literal so the return type stays exact. */
export const SEO_LOCALES = ['en', 'fr', 'de'] as const;

export type SeoLocale = (typeof SEO_LOCALES)[number];

export interface Alternates {
  canonical: string;
  languages: Record<string, string>;
}

/**
 * `/docs/mcp`, `docs/mcp` and `/docs/mcp/` all name the same page. One shape
 * reaches the URL so two callers writing the path differently cannot produce
 * two canonicals for one document.
 */
function normalizePath(path: string): string {
  const trimmed = path.trim().replace(/\/+$/, '');
  if (trimmed === '' || trimmed === '/') return '';
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
}

/**
 * The absolute URL of `path` in `locale`. English lives at the root since
 * 2026-09-05 (audit n° 28): `https://ibanforge.com/docs`, and the home is
 * `https://ibanforge.com/`, the URL every inbound link already carries.
 */
export function urlFor(locale: string, path: string = '/'): string {
  return `${SITE_URL}${localePath(locale, normalizePath(path) || '/')}`;
}

/**
 * The `alternates` block for one page: its own canonical, plus the same page in
 * every language. `x-default` points at English, the version served to a reader
 * we have no better match for.
 */
export function alternatesFor(locale: string, path: string = '/'): Alternates {
  const languages: Record<string, string> = {};
  for (const l of SEO_LOCALES) {
    languages[l] = urlFor(l, path);
  }
  languages['x-default'] = urlFor('en', path);
  return { canonical: urlFor(locale, path), languages };
}

/**
 * The share card generated by `app/[locale]/opengraph-image.tsx`.
 *
 * Next attaches that file-convention image on its own, but only while the page
 * does not declare an `openGraph` object of its own — and a page's object
 * REPLACES the segment's rather than merging with it. The docs and the blog
 * both declared one without `images`, which is how 116 of 170 pages ended up
 * with no `og:image` while announcing `twitter:card: summary_large_image`
 * (WEB-12, audit 2026-09-01). A page that sets `openGraph` names the image.
 */
export function ogImageFor(locale: string): { url: string; width: number; height: number } {
  const known = (SEO_LOCALES as readonly string[]).includes(locale) ? locale : 'en';
  return { url: urlFor(known, '/opengraph-image'), width: 1200, height: 630 };
}
